name: fish
dependencies:
  - python=3.12
  - python-graphviz
  - black
  - pip
  - pip:
    - git+https://github.com/wahabk/ctfishpy  # This is most packages
    - torchviz
    - ray[tune]
    - torchviz