# User defined config, depends on where your files are etc.
rdsf_dir: '/home/mh19137/zebrafish_rdsf/smb-share:server=rdsfcifs.acrc.bris.ac.uk,share=zebrafish_osteoarthritis/'

model_params:
  # Things you probably won't need to change - I just kept them here to keep all the params in one place
  spatial_dims: 3
  n_classes: 2 # 5  # 4 bones + background
  in_channels: 1  # Our images are greyscale
  # Things you might want to change
  n_layers: 6
  n_initial_filters: 16  # Think this has to be a square number
  kernel_size: 7
  stride: 2
  dropout: 0.015

# Other model parameters that aren't needed by the constructor
learning_rate: 0.0026
optimiser: "Adam"  # Must be one of the torch.optim optimisers
patch_size: 32,32,32  # Comma-separated; (16,16,16) causes issues (not sure why)
batch_size: 8